services:
  client:
    build:
      context: .
    ports:
      - "3000:5173"
    depends_on:
      - server
    environment:
      - VITE_HOST=0.0.0.0

  server:
    build:
      context: ../../go
    ports:
      - "8080:8080"